services:
  game_server:
    build: ./GameServer
    environment:
      WEB_CLIENT: ${WEB_CLIENT}
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      JWT_KEY: ${JWT_KEY}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
      ASPNETCORE_ENVIRONMENT: ${ENVIRONMENT}
      REDIS_CONNECTION_STRING: ${DATABASE_CONNECTION_URL}
      ASPNETCORE_URLS: https://+:443;http://+:80
    networks:
      - database
  matchmaking:
    environment:
      WEB_CLIENT: ${WEB_CLIENT}
      ASPNETCORE_ENVIRONMENT: ${ENVIRONMENT}
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      REDIS_CONNECTION_STRING: ${DATABASE_CONNECTION_URL}
      ASPNETCORE_URLS: https://+:443;http://+:80
    networks:
      - database
networks:
  database:
